app:
  port: 10001
server:
#  应该统一的提供 rpc 地址，而不是依靠这个配置表，实际这个配置表不应该这样写 默认提供主网的 rpc 地址，用户可以自己添加网络
  rpc: https://rpc.ankr.com/polygon_mumbai

engines:
  # 以太坊主币
  - network: Polygon
    rpc: https://gateway.tenderly.co/public/polygon-mumbai
  - network: Goerli
    rpc: https://ethereum-goerli.publicnode.com
  - network : Core
    rpc: https://rpc.test.btcs.network