app:
  port: 10001
engines:
#  - coin_name: ETH
#    contract:
#    contract_type:
#    protocol: eth
#    rpc: https://ropsten.infura.io/v3/adee4ead47844d238802431fcb7683c6
#    file: data/eth
#    wallet_prefix: wallet-
#    hash_prefix: hash-
#    block_init: 0
#    block_after_time: 1
#    receipt_count: 20
#    receipt_after_time: 1
#    collection_after_time: 2
#    collection_count: 10
#    collection_max: 10
#    collection_address: 0x785380b6012648d0DEeE1F66ac18657Db2240789
#    confirms: 1
#    recharge_notify_url: http://localhost:10001/api/withdraw
#    withdraw_notify_url: http://localhost:10001/api/withdraw
#    withdraw_private_key: 61774dacba914e5675eef6c616df85c61d7c8917f56ee77f547a140f8f982d31
#    decimals: 18
#  - coin_name: TEST
#    contract: 0xeDc4019BCBdA0f7acCBB4833ffF54d618d9b7f82
#    contract_type:
#    protocol: eth
#    rpc: https://ropsten.infura.io/v3/adee4ead47844d238802431fcb7683c6
#    file: data/usdt
#    wallet_prefix: wallet-
#    hash_prefix: hash-
#    block_init: 0
#    block_after_time: 1
#    receipt_count: 1
#    receipt_after_time: 1
#    collection_after_time: 1
#    collection_count: 10
#    collection_max: 15
#    collection_address: 0x785380b6012648d0DEeE1F66ac18657Db2240789
#    confirms: 1
#    recharge_notify_url: https://mainnet.infura.io
#    withdraw_notify_url: https://mainnet.infura.io
#    withdraw_private_key: 61774dacba914e5675eef6c616df85c61d7c8917f56ee77f547a140f8f982d31
#    decimals: 18

  - coin_name: TRX
    contract:
    contract_type:
    protocol: trx
    rpc: grpc.shasta.trongrid.io:50051
    file: data/trx
    wallet_prefix: wallet-
    hash_prefix: hash-
    block_init: 0
    block_after_time: 3
    receipt_count: 20
    receipt_after_time: 1
    collection_after_time: 2
    collection_count: 10
    collection_max: 10
    collection_address: TYBpNWMNHPyk1hBbY1SRr2RQebF39iFk7z
    confirms: 6
    recharge_notify_url: http://localhost:10001/api/withdraw
    withdraw_notify_url: http://localhost:10001/api/withdraw
    withdraw_private_key: a0e0ac9b3a1ee1a27411642b7ff60030887c6b78c89d498aba49adedceb4233b
    decimals: 18