app:
  port: 10001
engines:
  - coin_name: ETH
    contract:
    protocol: eth
    rpc: https://ropsten.infura.io/v3/adee4ead47844d238802431fcb7683c6
    file: data/eth
    wallet_prefix: wallet-
    hash_prefix: hash-
    block_init: 11828416
    block_after_time: 1
    receipt_count: 20
    receipt_after_time: 1
    collection_after_time: 2
    collection_count: 10
    collection_max: 10
    collection_address: 0x785380b6012648d0DEeE1F66ac18657Db2240789
    confirms: 1
    recharge_notify_url: http://localhost:10001/api/withdraw
    withdraw_notify_url: http://localhost:10001/api/withdraw
    withdraw_private_key: 61774dacba914e5675eef6c616df85c61d7c8917f56ee77f547a140f8f982d31
    decimals: 18
#  - coin_name: TEST
#    contract: 0xeDc4019BCBdA0f7acCBB4833ffF54d618d9b7f82
#    protocol: eth
#    rpc: https://ropsten.infura.io/v3/adee4ead47844d238802431fcb7683c6
#    file: data/usdt
#    wallet_prefix: wallet-
#    hash_prefix: hash-
#    block_init: 11824838
#    block_after_time: 1
#    receipt_count: 1
#    receipt_after_time: 1
#    collection_after_time: 1
#    collection_count: 10
#    collection_max: 15
#    collection_address: 0x785380b6012648d0DEeE1F66ac18657Db2240789
#    confirms: 1
#    recharge_notify_url: https://mainnet.infura.io
#    withdraw_notify_url: https://mainnet.infura.io
#    withdraw_private_key: 61774dacba914e5675eef6c616df85c61d7c8917f56ee77f547a140f8f982d31
#    decimals: 18